server:
  port: 8002
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      config:
        # 开启文件配置中心
        enabled: true
        # 配置文件夹前缀
        prefix: sample-config
        # 配置默认文件夹
        defaultContext: ${spring.application.name}
        # 配置默认key
#        data-key: data
        # 配置文件环境分隔符
#        profileSeparator: ','
        # 配置文件格式 eg: 1.8 jdk 可能存在冲突需要更新版本
        format: YAML
        # 定时刷新配置
        watch:
          delay: 1000
          enabled: true
  application:
    name: sample-service
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      rate: 10
  boot:
    admin:
      client:
        url: http://127.0.0.1:8003
#  security:
#    user:
#      name: actuator
#      password: 123456
simple4h:
  auto:
    configuration:
      word: abcabcabc
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true