server:
  port: 8002
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.60.4:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:9949
  application:
    name: sample-service
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      rate: 10
  boot:
    admin:
      client:
        url: http://127.0.0.1:8003
#  security:
#    user:
#      name: actuator
#      password: 123456
simple4h:
  auto:
    configuration:
      word: abcabcabc
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true