server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.60.4:8848
  application:
    name: sample-service
simple4h:
  auto:
    configuration:
      word: abcabcabc