spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      DATA_ID: gateway-config
      GROUP: GATEWAY_GROUP
      discovery:
        server-addr: 39.108.60.4:8848
server:
  port: 8000