spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.60.4:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: demo_service
          # consul 获取的服务名称 lb -> load balance
          uri: lb://demo-service
          predicates:
            - Path=/demo/**
          # 过滤 去掉路径中的 /orderApi
        #          filters:
        #            - StripPrefix=1
        - id: sample_service
          # consul 获取的服务名称 lb -> load balance
          uri: lb://sample-service
          predicates:
            - Path=/sample/**
          # 过滤 去掉路径中的 /api
  #          filters:
  #            - StripPrefix=1
server:
  port: 10000