spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: demo_service
          uri: lb://demo-service
          predicates:
            - Path=/demo_service/demo/**
          filters:
            - StripPrefix=1
        - id: sample_service
          uri: lb://sample-service
          predicates:
            - Path=/sample_service/sample/**
          filters:
            - StripPrefix=1
server:
  port: 8000