spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          # 不允许通过服务名访问
          enabled: false
      routes:
        - id: demo_service
          uri: lb://demo-service
          predicates:
            - Path=/demo/**
          filters:
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的上限
                redis-rate-limiter.burstCapacity: 1
                # 使用SpEL表达式从Spring容器中获取Bean对象
                key-resolver: "#{@ipKeyResolver}"
        - id: sample_service
          uri: lb://sample-service
          predicates:
            - Path=/sample/**
          filters:
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的上限
                redis-rate-limiter.burstCapacity: 1
                # 使用SpEL表达式从Spring容器中获取Bean对象
                key-resolver: "#{@pathKeyResolver}"
    loadbalancer:
      ribbon:
        enabled: false
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      rate: 10
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 8
        max-idle: 16
        max-wait: 300ms
        max-active: 32
  boot:
    admin:
      client:
        url: http://127.0.0.1:8003
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true