spring:
  application:
    name: admin-service
  cloud:
    nacos:
      discovery:
        server-addr: 39.108.60.4:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:9949
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      rate: 10
  boot:
    admin:
      discovery:
        ignored-services: nacos
server:
  port: 8003
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true