spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300ms
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8